apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scaletestapp-sm
  namespace: default
  labels:
    serviceMonitorSelector: prometheus
    release: prometheus-operator
spec:
  endpoints:
    - interval: 10s
      targetPort: 80
      path: /metrics
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      prometheus-monitored: "true"
