apiVersion: v1
kind: Service
metadata:
  name: scaletestapp-srv
  labels:
    app: scaletestapp
    prometheus-monitored: "true"
spec:
  selector:
    app: scaletestapp
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort
